import os
import datetime
from django.utils import timezone
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas

def get_django_logo_path():
  possible_paths = [
    os.path.join(os.path.dirname(__file__), '../../../frontend/public/assets/logo.png'),
    os.path.join(os.path.dirname(__file__), '../../frontend/public/assets/logo.png'),
    'J:/Crimepilot/frontend/public/assets/logo.png'
  ]
  for p in possible_paths:
    if os.path.exists(p):
      return p
  return None

class NumberedCanvas(canvas.Canvas):
  """
  Two-pass canvas for dynamic page count, logo header, faint logo & text watermark, and footer.
  """
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self._saved_page_states = []

  def showPage(self):
    self._saved_page_states.append(dict(self.__dict__))
    self._startPage()

  def save(self):
    num_pages = len(self._saved_page_states)
    for state in self._saved_page_states:
      self.__dict__.update(state)
      self.draw_page_decorations(num_pages)
      super().showPage()
    super().save()

  def draw_page_decorations(self, page_count):
    logo_path = get_django_logo_path()

    # 1. Government Header Banner (Top)
    self.setFillColor(colors.HexColor('#0B1220'))
    self.rect(0, 744, 595.28, 98, stroke=0, fill=1)

    self.setFillColor(colors.HexColor('#00D9FF'))
    self.rect(0, 740.5, 595.28, 3.5, stroke=0, fill=1)

    # Draw Logo in Header Top-Left
    text_start_x = 36
    if logo_path:
      try:
        self.drawImage(logo_path, 36, 768, width=44, height=44, preserveAspectRatio=True, mask='auto')
        text_start_x = 92
      except Exception as e:
        print('Django logo draw warning:', e)

    self.setFillColor(colors.HexColor('#00D9FF'))
    self.setFont('Helvetica-Bold', 7.5)
    self.drawString(text_start_x, 818, 'GOVERNMENT OF INDIA // NATIONAL CRIME INTELLIGENCE COMMAND')

    self.setFillColor(colors.HexColor('#FFFFFF'))
    self.setFont('Helvetica-Bold', 13.5)
    self.drawString(text_start_x, 797, 'CRIMEPILOT AI — NATIONAL CRIME INTELLIGENCE PLATFORM')

    self.setFillColor(colors.HexColor('#7DD3FC'))
    self.setFont('Helvetica-Bold', 9.5)
    self.drawString(text_start_x, 776, 'OFFICIAL CRIME INVESTIGATION REPORT')

    self.setFillColor(colors.HexColor('#94A3B8'))
    self.setFont('Helvetica', 7.5)
    self.drawString(text_start_x, 757, 'CONFIDENTIAL & RESTRICTED DOCUMENT — GOVERNMENT ACCESS ONLY')

    # 2. Footer with Small Logo on Left
    self.setStrokeColor(colors.HexColor('#CBD5E1'))
    self.setLineWidth(0.75)
    self.line(36, 36, 559.28, 36)

    footer_text_x = 36
    if logo_path:
      try:
        self.drawImage(logo_path, 36, 18, width=14, height=14, preserveAspectRatio=True, mask='auto')
        footer_text_x = 56
      except Exception:
        pass

    self.setFillColor(colors.HexColor('#64748B'))
    self.setFont('Helvetica', 7.5)
    self.drawString(footer_text_x, 22, 'CrimePilot AI | Official National Crime Intelligence Platform | Official Report')
    page_str = f'Page {self._pageNumber} of {page_count}'
    self.drawRightString(559.28, 22, page_str)

def timezone_now_str():
  return timezone.now().strftime('%Y-%m-%d %H:%M:%S')

def generate_report_pdf(response, title, subtitle, data, date_range):
  """
  Generates an ultra-premium enterprise PDF report using ReportLab
  and writes it directly to the response stream.
  """
  doc = SimpleDocTemplate(
    response,
    pagesize=A4,
    leftMargin=36,
    rightMargin=36,
    topMargin=106,
    bottomMargin=48
  )

  story = []
  styles = getSampleStyleSheet()

  cell_style = ParagraphStyle(
    'GridCell',
    parent=styles['Normal'],
    fontName='Helvetica',
    fontSize=7.5,
    leading=10,
    textColor=colors.HexColor('#0F172A')
  )

  header_cell_style = ParagraphStyle(
    'HeaderCell',
    parent=styles['Normal'],
    fontName='Helvetica-Bold',
    fontSize=7.5,
    leading=10,
    textColor=colors.white
  )

  # 1. 6 Report Information Cards (2 rows x 3 cols)
  report_id = f"NCIP-RPT-{int(datetime.datetime.now().timestamp())}"
  time_str = timezone_now_str()
  period_str = date_range or '20 Jul - 31 Jul 2026'

  info_data = [
    [
      Paragraph("<font color='#64748B'><b>REPORT ID</b></font><br/><font color='#0284C7'><b>" + report_id + "</b></font>", cell_style),
      Paragraph("<font color='#64748B'><b>GENERATED DATE</b></font><br/><b>" + time_str + "</b>", cell_style),
      Paragraph("<font color='#64748B'><b>REPORT PERIOD</b></font><br/><b>" + period_str + "</b>", cell_style)
    ],
    [
      Paragraph("<font color='#64748B'><b>GENERATED BY</b></font><br/><b>Admin Command</b>", cell_style),
      Paragraph("<font color='#64748B'><b>CLASSIFICATION</b></font><br/><font color='#B91C1C'><b>Internal Use</b></font>", cell_style),
      Paragraph("<font color='#64748B'><b>STATUS</b></font><br/><font color='#15803D'><b>Official</b></font>", cell_style)
    ]
  ]

  info_table = Table(info_data, colWidths=[174, 174, 175])
  info_table.setStyle(TableStyle([
    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
    ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#E2E8F0')),
    ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
    ('PADDING', (0,0), (-1,-1), 6),
  ]))

  story.append(info_table)
  story.append(Spacer(1, 14))

  # 2. 5 Independent Summary Statistics Cards
  cases_list = list(data)
  total_cases = len(cases_list)
  solved_cases = len([c for c in cases_list if getattr(c, 'status', '') in ['Solved', 'Closed']])
  pending_cases = len([c for c in cases_list if getattr(c, 'status', '') in ['Open', 'Under Investigation', 'Reported', 'Pending']])
  high_priority = len([c for c in cases_list if getattr(c, 'priority', '') == 'High'])
  critical_cases = len([c for c in cases_list if getattr(c, 'priority', '') == 'Critical'])

  stat_data = [
    [
      Paragraph("<font color='#64748B'>📁 <b>TOTAL CASES</b></font><br/><br/><font size=16 color='#0369A1'><b>" + str(total_cases) + "</b></font>", cell_style),
      Paragraph("<font color='#64748B'>✅ <b>SOLVED CASES</b></font><br/><br/><font size=16 color='#15803D'><b>" + str(solved_cases) + "</b></font>", cell_style),
      Paragraph("<font color='#64748B'>⏳ <b>PENDING CASES</b></font><br/><br/><font size=16 color='#B45309'><b>" + str(pending_cases) + "</b></font>", cell_style),
      Paragraph("<font color='#64748B'>⚠️ <b>HIGH PRIORITY</b></font><br/><br/><font size=16 color='#C2410C'><b>" + str(high_priority) + "</b></font>", cell_style),
      Paragraph("<font color='#64748B'>🚨 <b>CRITICAL CASES</b></font><br/><br/><font size=16 color='#B91C1C'><b>" + str(critical_cases) + "</b></font>", cell_style),
    ]
  ]

  stat_table = Table(stat_data, colWidths=[104, 104, 104, 105, 106])
  stat_table.setStyle(TableStyle([
    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
    ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#E2E8F0')),
    ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
    ('PADDING', (0,0), (-1,-1), 12),
  ]))

  story.append(stat_table)
  story.append(Spacer(1, 14))

  # 3. Two Square Summary Cards
  category_counts = {}
  station_counts = {}
  for c in cases_list:
    cat_name = c.crime_category.name if getattr(c, 'crime_category', None) else 'Unassigned'
    stn_name = c.location.police_station if getattr(c, 'location', None) else 'HQ Unit'
    category_counts[cat_name] = category_counts.get(cat_name, 0) + 1
    station_counts[stn_name] = station_counts.get(stn_name, 0) + 1

  cat_items = [f"• <b>{k}</b>: {v} case(s)" for k, v in list(category_counts.items())[:3]]
  stn_items = [f"• <b>{k}</b>: {v} case(s)" for k, v in list(station_counts.items())[:3]]

  cat_summary_text = "<br/>".join(cat_items) if cat_items else "No category records available."
  stn_summary_text = "<br/>".join(stn_items) if stn_items else "No station records available."

  summary_rows = [
    [
      Paragraph("<font color='#0F172A'><b>📊 CRIME CATEGORY SUMMARY</b></font><br/><br/>" + cat_summary_text, cell_style),
      Paragraph("<font color='#0F172A'><b>🏛️ POLICE STATION SUMMARY</b></font><br/><br/>" + stn_summary_text, cell_style)
    ]
  ]

  summary_table = Table(summary_rows, colWidths=[261, 262])
  summary_table.setStyle(TableStyle([
    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
    ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#E2E8F0')),
    ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
    ('PADDING', (0,0), (-1,-1), 10),
  ]))

  story.append(summary_table)
  story.append(Spacer(1, 16))

  # 4. Incident Cases Table with Increased Row Height & Padding
  table_header = [
    Paragraph("CASE ID", header_cell_style),
    Paragraph("CITIZEN NAME", header_cell_style),
    Paragraph("CATEGORY", header_cell_style),
    Paragraph("POLICE STATION", header_cell_style),
    Paragraph("OFFICER", header_cell_style),
    Paragraph("PRIORITY", header_cell_style),
    Paragraph("STATUS", header_cell_style),
    Paragraph("DATE", header_cell_style)
  ]

  cases_table_data = [table_header]

  for c in cases_list:
    cat_name = c.crime_category.name if getattr(c, 'crime_category', None) else 'Unassigned'
    stn_name = c.location.police_station if getattr(c, 'location', None) else 'HQ Unit'
    officer_name = c.assigned_officer.name if getattr(c, 'assigned_officer', None) else 'Unassigned'
    citizen_name = c.citizen_name if hasattr(c, 'citizen_name') else 'Anonymous'
    date_val = c.date.strftime('%Y-%m-%d') if getattr(c, 'date', None) else 'N/A'
    prio_val = getattr(c, 'priority', 'Medium')
    status_val = getattr(c, 'status', 'Open')

    p_color = '#C2410C'
    if prio_val == 'High': p_color = '#991B1B'
    elif prio_val == 'Critical': p_color = '#9D174D'
    elif prio_val == 'Low': p_color = '#166534'

    s_color = '#0369A1'
    if status_val in ['Closed', 'Solved']: s_color = '#15803D'
    elif status_val in ['Under Investigation', 'Assigned']: s_color = '#B45309'

    cases_table_data.append([
      Paragraph(f"<b>{c.crime_id or 'N/A'}</b>", cell_style),
      Paragraph(citizen_name, cell_style),
      Paragraph(cat_name, cell_style),
      Paragraph(stn_name, cell_style), # Wraps automatically in 110pt column
      Paragraph(officer_name, cell_style),
      Paragraph(f"<font color='{p_color}'><b>{prio_val}</b></font>", cell_style),
      Paragraph(f"<font color='{s_color}'><b>{status_val}</b></font>", cell_style),
      Paragraph(date_val, cell_style)
    ])

  # No Data State centered inside card
  if len(cases_table_data) == 1:
    no_data_text = Paragraph(
      "<font size=20>📂</font><br/><br/>"
      "<b>No crime records matched the selected filters.</b><br/><br/>"
      "<font color='#64748B'>Try expanding the report period<br/>or modifying the selected filters.</font>",
      ParagraphStyle('NoDataStyle', parent=styles['Normal'], alignment=1, leading=14, textColor=colors.HexColor('#0F172A'))
    )
    no_data_table = Table([[no_data_text]], colWidths=[523])
    no_data_table.setStyle(TableStyle([
      ('BACKGROUND', (0,0), (-1,-1), colors.white),
      ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#E2E8F0')),
      ('PADDING', (0,0), (-1,-1), 24),
      ('ALIGN', (0,0), (-1,-1), 'CENTER'),
    ]))
    story.append(no_data_table)
  else:
    cases_table = Table(cases_table_data, colWidths=[52, 70, 74, 110, 68, 48, 55, 46])
    cases_table.setStyle(TableStyle([
      ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0F172A')),
      ('TEXTCOLOR', (0,0), (-1,0), colors.white),
      ('PADDING', (0,0), (-1,-1), 6),
      ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
      ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#F8FAFC')]),
    ]))
    story.append(cases_table)

  doc.build(story, canvasmaker=NumberedCanvas)


class FIRNumberedCanvas(canvas.Canvas):
  """
  Two-pass canvas for CrimePilot AI Official Digital FIR PDF document.
  Provides clean CrimePilot header with logo, page numbers, and modern official footer.
  """
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self._saved_page_states = []

  def showPage(self):
    self._saved_page_states.append(dict(self.__dict__))
    self._startPage()

  def save(self):
    num_pages = len(self._saved_page_states)
    for state in self._saved_page_states:
      self.__dict__.update(state)
      self.draw_page_decorations(num_pages)
      super().showPage()
    super().save()

  def draw_page_decorations(self, page_count):
    logo_path = get_django_logo_path()
    
    text_x = 36
    if logo_path:
      try:
        self.drawImage(logo_path, 36, 785, width=44, height=44, preserveAspectRatio=True, mask='auto')
        text_x = 90
      except Exception:
        pass

    # Line 1: CRIMEPILOT AI
    self.setFillColor(colors.HexColor('#0B1220'))
    self.setFont('Helvetica-Bold', 14)
    self.drawString(text_x, 818, 'CRIMEPILOT AI')

    # Line 2: Digital Crime Intelligence Platform
    self.setFillColor(colors.HexColor('#0284C7'))
    self.setFont('Helvetica-Bold', 8.5)
    self.drawString(text_x, 807, 'Digital Crime Intelligence Platform')

    # Line 3: OFFICIAL FIRST INFORMATION REPORT (FIR)
    self.setFillColor(colors.HexColor('#0B1220'))
    self.setFont('Helvetica-Bold', 10.5)
    self.drawString(text_x, 793, 'OFFICIAL FIRST INFORMATION REPORT (FIR)')

    # Line 4: Secure Digital FIR System • Based on BNSS 2023 • BNS 2023 • BSA 2023
    self.setFillColor(colors.HexColor('#475569'))
    self.setFont('Helvetica', 7.5)
    self.drawString(text_x, 781, 'Secure Digital FIR System • Based on BNSS 2023 • BNS 2023 • BSA 2023')

    # Header Divider Line (Dark Navy & Cyan accent)
    self.setStrokeColor(colors.HexColor('#0B1220'))
    self.setLineWidth(1.5)
    self.line(36, 774, 559.28, 774)

    self.setStrokeColor(colors.HexColor('#00D9FF'))
    self.setLineWidth(1)
    self.line(36, 772.5, 559.28, 772.5)

    # Footer Line
    self.setStrokeColor(colors.HexColor('#CBD5E1'))
    self.setLineWidth(0.75)
    self.line(36, 36, 559.28, 36)

    # Footer Text as specified
    self.setFillColor(colors.HexColor('#0B1220'))
    self.setFont('Helvetica-Bold', 7.5)
    self.drawString(36, 23, 'CrimePilot AI • Secure Digital FIR Management Platform')
    self.setFillColor(colors.HexColor('#64748B'))
    self.setFont('Helvetica', 7)
    self.drawString(36, 13, 'Generated Digitally • QR Verified • Tamper Protected')

    page_str = f'Page {self._pageNumber} of {page_count}'
    self.setFont('Helvetica', 8)
    self.drawRightString(559.28, 20, page_str)


def generate_official_indian_fir_pdf(response, crime):
  """
  Generates an official CrimePilot AI Digital First Information Report (FIR) PDF
  under BNSS 2023, BNS 2023, and BSA 2023, formatted dynamically from the crime case object.
  """
  doc = SimpleDocTemplate(
    response,
    pagesize=A4,
    leftMargin=36,
    rightMargin=36,
    topMargin=78,
    bottomMargin=48
  )

  story = []
  styles = getSampleStyleSheet()

  # Custom Paragraph Styles with CrimePilot Theme (#0B1220, #00D9FF, #0284C7)
  section_heading_style = ParagraphStyle(
    'FIRSectionHeading',
    parent=styles['Normal'],
    fontName='Helvetica-Bold',
    fontSize=10,
    leading=13,
    textColor=colors.HexColor('#0B1220'),
    spaceBefore=8,
    spaceAfter=4
  )

  cell_lbl = ParagraphStyle(
    'FIRCellLbl',
    parent=styles['Normal'],
    fontName='Helvetica-Bold',
    fontSize=8,
    leading=10,
    textColor=colors.HexColor('#334155')
  )

  cell_val = ParagraphStyle(
    'FIRCellVal',
    parent=styles['Normal'],
    fontName='Helvetica',
    fontSize=8.5,
    leading=11,
    textColor=colors.HexColor('#0F172A')
  )

  cell_val_bold = ParagraphStyle(
    'FIRCellValBold',
    parent=styles['Normal'],
    fontName='Helvetica-Bold',
    fontSize=8.5,
    leading=11,
    textColor=colors.HexColor('#0B1220')
  )

  # Data Extraction
  stn_name = crime.location.police_station if crime.location else 'Central Police Station'
  district = crime.location.city if crime.location else 'Ahmedabad'
  state = crime.location.state if crime.location else 'Gujarat'
  cat_name = crime.crime_category.name if crime.crime_category else 'General Offence'

  fir_no = f"FIR-{crime.crime_id}"
  case_no = crime.crime_id
  reg_date = crime.created_at.strftime('%Y-%m-%d') if hasattr(crime, 'created_at') and crime.created_at else (crime.date.strftime('%Y-%m-%d') if crime.date else '2026-08-02')
  reg_time = crime.created_at.strftime('%H:%M:%S IST') if hasattr(crime, 'created_at') and crime.created_at else (str(crime.time) if crime.time else '10:30:00 IST')
  gd_no = f"GD-2026-00{crime.id}"

  # Complainant Details
  cit_obj = crime.citizen
  u_obj = cit_obj.user if cit_obj else None
  cit_name = u_obj.name if u_obj else (getattr(crime, 'citizen_name', 'Anonymous'))
  cit_gender = getattr(cit_obj, 'gender', 'N/A') or 'Male/Female'
  cit_mobile = getattr(cit_obj, 'mobile', 'N/A') or 'N/A'
  cit_email = u_obj.email if u_obj else 'N/A'
  cit_addr = getattr(cit_obj, 'address', 'N/A') or 'N/A'
  cit_city = getattr(cit_obj, 'city', district) or district
  cit_state = getattr(cit_obj, 'state', state) or state
  cit_pincode = getattr(cit_obj, 'pincode', 'N/A') or 'N/A'
  cit_id_type = getattr(cit_obj, 'identity_type', 'Aadhaar Card') or 'Aadhaar Card'
  cit_id_no = getattr(cit_obj, 'identity_number', 'N/A') or 'N/A'

  # BNS legal sections resolution
  cat_lower = cat_name.lower()
  if 'cyber' in cat_lower or 'fraud' in cat_lower or 'netbanking' in cat_lower or 'online' in cat_lower:
    bns_sections = "BNS Sec 318(4) [Cheating], IT Act Sec 66D [Impersonation by Computer]"
  elif 'theft' in cat_lower or 'vehicle' in cat_lower or 'stolen' in cat_lower:
    bns_sections = "BNS Sec 305 [Theft in Dwelling / Motor Vehicle]"
  elif 'robbery' in cat_lower or 'snatching' in cat_lower or 'extortion' in cat_lower:
    bns_sections = "BNS Sec 304 [Snatching], BNS Sec 309 [Robbery]"
  elif 'assault' in cat_lower or 'violence' in cat_lower or 'hurt' in cat_lower:
    bns_sections = "BNS Sec 115(2) [Voluntarily Causing Hurt], BNS Sec 126(2)"
  elif 'domestic' in cat_lower or 'cruelty' in cat_lower:
    bns_sections = "BNS Sec 85 [Cruelty by Husband / Relatives]"
  elif 'drug' in cat_lower or 'narcotic' in cat_lower or 'ndps' in cat_lower:
    bns_sections = "NDPS Act Sec 20 / Sec 22"
  elif 'accident' in cat_lower or 'hit' in cat_lower:
    bns_sections = "BNS Sec 106(1) [Rash & Negligent Act]"
  else:
    bns_sections = "BNS Sec 318 [Cheating], BNS Sec 303 [Theft]"

  # Sub-Header Banner
  story.append(Spacer(1, 4))
  header_table = Table([
    [
      Paragraph(f"<b>POLICE STATION:</b> {stn_name.upper()}", cell_lbl),
      Paragraph(f"<b>DISTRICT:</b> {district.upper()}", cell_lbl),
      Paragraph(f"<b>STATE:</b> {state.upper()}", cell_lbl)
    ]
  ], colWidths=[174, 174, 175])
  header_table.setStyle(TableStyle([
    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
    ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#0B1220')),
    ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
    ('PADDING', (0,0), (-1,-1), 6),
  ]))
  story.append(header_table)
  story.append(Spacer(1, 8))

  # 1. CASE INFORMATION
  story.append(Paragraph("1. CASE INFORMATION", section_heading_style))
  case_info = [
    [
      Paragraph("FIR Number", cell_lbl), Paragraph(fir_no, cell_val_bold),
      Paragraph("Case Reference ID", cell_lbl), Paragraph(case_no, cell_val)
    ],
    [
      Paragraph("Police Station", cell_lbl), Paragraph(stn_name, cell_val),
      Paragraph("District / State", cell_lbl), Paragraph(f"{district}, {state}", cell_val)
    ],
    [
      Paragraph("Date of Registration", cell_lbl), Paragraph(reg_date, cell_val),
      Paragraph("Time of Registration", cell_lbl), Paragraph(reg_time, cell_val)
    ],
    [
      Paragraph("GD Entry Number", cell_lbl), Paragraph(gd_no, cell_val),
      Paragraph("Complaint Type", cell_lbl), Paragraph(cat_name, cell_val)
    ],
    [
      Paragraph("Priority Level", cell_lbl), Paragraph(f"<b>{crime.priority}</b>", cell_val),
      Paragraph("Current Status", cell_lbl), Paragraph(f"<b>{crime.status}</b>", cell_val_bold)
    ]
  ]
  t_case = Table(case_info, colWidths=[110, 151, 110, 152])
  t_case.setStyle(TableStyle([
    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
    ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#F8FAFC')),
    ('BACKGROUND', (2,0), (2,-1), colors.HexColor('#F8FAFC')),
    ('PADDING', (0,0), (-1,-1), 5),
  ]))
  story.append(t_case)
  story.append(Spacer(1, 8))

  # 2. COMPLAINANT / INFORMANT DETAILS
  story.append(Paragraph("2. COMPLAINANT / INFORMANT DETAILS", section_heading_style))
  comp_info = [
    [
      Paragraph("Full Name", cell_lbl), Paragraph(f"<b>{cit_name}</b>", cell_val),
      Paragraph("Gender / Age", cell_lbl), Paragraph(f"{cit_gender}", cell_val)
    ],
    [
      Paragraph("Mobile Number", cell_lbl), Paragraph(cit_mobile, cell_val),
      Paragraph("Email Address", cell_lbl), Paragraph(cit_email, cell_val)
    ],
    [
      Paragraph("Residential Address", cell_lbl), Paragraph(f"{cit_addr}, {cit_city}, {cit_state} - {cit_pincode}", cell_val),
      Paragraph("Identity Proof", cell_lbl), Paragraph(f"{cit_id_type}: {cit_id_no}", cell_val)
    ]
  ]
  t_comp = Table(comp_info, colWidths=[110, 151, 110, 152])
  t_comp.setStyle(TableStyle([
    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
    ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#F8FAFC')),
    ('BACKGROUND', (2,0), (2,-1), colors.HexColor('#F8FAFC')),
    ('PADDING', (0,0), (-1,-1), 5),
  ]))
  story.append(t_comp)
  story.append(Spacer(1, 8))

  # 3. INCIDENT DETAILS & LOCATION
  story.append(Paragraph("3. INCIDENT DETAILS & LOCATION OF OCCURRENCE", section_heading_style))
  inc_date_val = crime.date.strftime('%Y-%m-%d') if crime.date else reg_date
  inc_time_val = str(crime.time) if crime.time else reg_time
  gps_coords = f"Lat: {getattr(crime.location, 'latitude', 'N/A')}, Long: {getattr(crime.location, 'longitude', 'N/A')}" if (crime.location and hasattr(crime.location, 'latitude')) else f"Precinct Jurisdiction ({stn_name})"
  
  inc_info = [
    [
      Paragraph("Date of Incident", cell_lbl), Paragraph(inc_date_val, cell_val),
      Paragraph("Time of Incident", cell_lbl), Paragraph(inc_time_val, cell_val)
    ],
    [
      Paragraph("Place of Incident", cell_lbl), Paragraph(f"{stn_name}, {district}", cell_val),
      Paragraph("GPS Location", cell_lbl), Paragraph(gps_coords, cell_val)
    ],
    [
      Paragraph("Crime Category", cell_lbl), Paragraph(cat_name, cell_val),
      Paragraph("Applicable BNS Sections", cell_lbl), Paragraph(f"<b>{bns_sections}</b>", cell_val_bold)
    ],
    [
      Paragraph("Complaint Description", cell_lbl),
      Paragraph(f"{crime.description}", cell_val),
      Paragraph("Investigation Precinct", cell_lbl),
      Paragraph(stn_name, cell_val)
    ]
  ]
  t_inc = Table(inc_info, colWidths=[110, 151, 110, 152])
  t_inc.setStyle(TableStyle([
    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
    ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#F8FAFC')),
    ('BACKGROUND', (2,0), (2,-1), colors.HexColor('#F8FAFC')),
    ('PADDING', (0,0), (-1,-1), 5),
  ]))
  story.append(t_inc)
  story.append(Spacer(1, 8))

  # 4. ACCUSED DETAILS
  story.append(Paragraph("4. ACCUSED DETAILS", section_heading_style))
  suspects = crime.suspects.all() if hasattr(crime, 'suspects') else []
  if suspects and len(suspects) > 0:
    accused_rows = [[Paragraph("NAME / ALIAS", cell_lbl), Paragraph("GENDER / AGE", cell_lbl), Paragraph("ADDRESS / DETAILS", cell_lbl)]]
    for s in suspects:
      accused_rows.append([
        Paragraph(f"<b>{s.name}</b> (Alias: {s.alias or 'N/A'})", cell_val),
        Paragraph(f"{s.gender or 'N/A'} / {s.age or 'N/A'} yrs", cell_val),
        Paragraph(s.address or 'Under Active Investigation', cell_val)
      ])
    t_acc = Table(accused_rows, colWidths=[180, 140, 203])
    t_acc.setStyle(TableStyle([
      ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
      ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#F1F5F9')),
      ('PADDING', (0,0), (-1,-1), 5),
    ]))
    story.append(t_acc)
  else:
    t_acc = Table([[Paragraph("<b>Accused Unknown</b> (Under Active Investigation by Precinct Personnel)", cell_val)]], colWidths=[523])
    t_acc.setStyle(TableStyle([
      ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
      ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
      ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t_acc)
  story.append(Spacer(1, 8))

  # 5. EVIDENCE & ATTACHMENTS
  story.append(Paragraph("5. EVIDENCE & DOCUMENTS ATTACHED", section_heading_style))
  evidences = crime.evidences.all() if hasattr(crime, 'evidences') else []
  if evidences and len(evidences) > 0:
    ev_rows = [[Paragraph("EVIDENCE ID", cell_lbl), Paragraph("TYPE", cell_lbl), Paragraph("DESCRIPTION / FILE", cell_lbl), Paragraph("DATE LOGGED", cell_lbl)]]
    for ev in evidences:
      ev_rows.append([
        Paragraph(f"EV-{ev.id}", cell_val),
        Paragraph(ev.type, cell_val),
        Paragraph(ev.description, cell_val),
        Paragraph(str(ev.collection_date or reg_date), cell_val)
      ])
    t_ev = Table(ev_rows, colWidths=[70, 90, 263, 100])
    t_ev.setStyle(TableStyle([
      ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
      ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#F1F5F9')),
      ('PADDING', (0,0), (-1,-1), 5),
    ]))
    story.append(t_ev)
  else:
    t_ev = Table([[Paragraph("No physical or digital evidence attached at initial filing.", cell_val)]], colWidths=[523])
    t_ev.setStyle(TableStyle([
      ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
      ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
      ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t_ev)
  story.append(Spacer(1, 8))

  # 6. POLICE DETAILS & INVESTIGATING OFFICER
  story.append(Paragraph("6. POLICE & INVESTIGATING OFFICER DETAILS", section_heading_style))
  off_obj = crime.officer
  off_user = off_obj.user if off_obj else None
  off_name = f"Inspector {off_user.name}" if off_user else "Assigned Personnel (Under Review)"
  off_badge = off_obj.badge_no if off_obj else "N/A"
  
  pol_info = [
    [
      Paragraph("Assigned Station", cell_lbl), Paragraph(stn_name, cell_val),
      Paragraph("Investigating Officer", cell_lbl), Paragraph(f"<b>{off_name}</b>", cell_val_bold)
    ],
    [
      Paragraph("Officer Rank", cell_lbl), Paragraph("Inspector of Police / IO", cell_val),
      Paragraph("Badge Number", cell_lbl), Paragraph(off_badge, cell_val)
    ]
  ]
  t_pol = Table(pol_info, colWidths=[110, 151, 110, 152])
  t_pol.setStyle(TableStyle([
    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
    ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#F8FAFC')),
    ('BACKGROUND', (2,0), (2,-1), colors.HexColor('#F8FAFC')),
    ('PADDING', (0,0), (-1,-1), 5),
  ]))
  story.append(t_pol)
  story.append(Spacer(1, 8))

  # 7. CASE TRACKING TIMELINE
  story.append(Paragraph("7. CASE INVESTIGATION TRACKING STAGES", section_heading_style))
  stages = ["Submitted", "Registered", "Assigned", "Investigation", "Evidence Review", "Charge Sheet", "Closed"]
  cur_status = str(crime.status).lower()
  
  stage_cells = []
  for idx, stg in enumerate(stages, 1):
    is_active = stg.lower() in cur_status or (stg == "Registered" and "open" in cur_status) or (stg == "Submitted" and True)
    bg_color = "#0B1220" if is_active else "#F1F5F9"
    txt_color = "#FFFFFF" if is_active else "#64748B"
    style_stg = ParagraphStyle(f'Stg{idx}', parent=styles['Normal'], alignment=1, fontSize=7, leading=9, textColor=colors.HexColor(txt_color), fontName='Helvetica-Bold' if is_active else 'Helvetica')
    stage_cells.append(Paragraph(f"{idx}. {stg.upper()}", style_stg))
    
  t_track = Table([stage_cells], colWidths=[74, 74, 74, 75, 75, 75, 76])
  t_track.setStyle(TableStyle([
    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
    ('PADDING', (0,0), (-1,-1), 6),
    ('ALIGN', (0,0), (-1,-1), 'CENTER'),
  ]))
  story.append(t_track)
  story.append(Spacer(1, 8))

  # 8. LEGAL PROVISIONS & APPLICABLE ACTS
  story.append(Paragraph("8. APPLICABLE STATUTORY LAWS & LEGAL PROVISIONS", section_heading_style))
  legal_info = [
    [
      Paragraph("Primary Offence BNS Sections", cell_lbl),
      Paragraph(f"<b>{bns_sections}</b>", cell_val_bold)
    ],
    [
      Paragraph("Procedural Law (BNSS, 2023)", cell_lbl),
      Paragraph("<b>BNSS Sec 173</b> (FIR Registration), <b>BNSS Sec 176</b> (Investigation Procedure), <b>BNSS Sec 187</b> (Police Report)", cell_val)
    ],
    [
      Paragraph("Evidence Rules (BSA, 2023)", cell_lbl),
      Paragraph("<b>BSA Sec 61</b> (Electronic Records Admissibility), <b>BSA Sec 63</b> (Digital Certificate Standards)", cell_val)
    ]
  ]
  t_legal = Table(legal_info, colWidths=[160, 363])
  t_legal.setStyle(TableStyle([
    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
    ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#F8FAFC')),
    ('PADDING', (0,0), (-1,-1), 5),
  ]))
  story.append(t_legal)
  story.append(Spacer(1, 14))

  # 9. OFFICIAL FOOTER & SEAL / SIGNATURE PLACEHOLDERS
  gen_time_str = timezone.now().strftime("%d %b %Y, %H:%M:%S IST")
  stamp_table_data = [
    [
      Paragraph("<font color='#0B1220'><b>DIGITAL SIGNATURE</b></font><br/><br/>[ DIGITALLY SIGNED & VERIFIED ]<br/><b>CrimePilot Command System</b><br/><font color='#64748B' size=7>Token ID: CP-SEC-" + str(crime.id) + "</font>", cell_val),
      Paragraph("<font color='#0B1220'><b>VERIFICATION QR CODE</b></font><br/><br/>[ QR CODE VERIFICATION ]<br/><b>Scan to verify FIR authenticity</b><br/><font color='#64748B' size=7>CrimePilot Verification Engine</font>", cell_val),
      Paragraph("<font color='#0B1220'><b>OFFICIAL SEAL</b></font><br/><br/>[ CRIMEPILOT PRECINCT SEAL ]<br/><b>" + stn_name.upper() + "</b><br/><font color='#64748B' size=7>Issued: " + gen_time_str + "</font>", cell_val)
    ]
  ]
  t_stamp = Table(stamp_table_data, colWidths=[174, 174, 175])
  t_stamp.setStyle(TableStyle([
    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#0B1220')),
    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
    ('ALIGN', (0,0), (-1,-1), 'CENTER'),
    ('PADDING', (0,0), (-1,-1), 8),
  ]))
  story.append(t_stamp)

  doc.build(story, canvasmaker=FIRNumberedCanvas)


