const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const getLogoPath = () => {
  const possiblePaths = [
    path.join(__dirname, '../../frontend/public/assets/logo.png'),
    path.join(__dirname, '../frontend/public/assets/logo.png'),
    'J:/Crimepilot/frontend/public/assets/logo.png'
  ];
  for (const p of possiblePaths) {
    if (fs.existsSync(p)) return p;
  }
  return null;
};

/**
 * Generates an ultra-premium, QRadar/PowerBI-grade government PDF intelligence report.
 * Pipes the generated PDF directly to the express response.
 */
const generateReportPDF = (res, title, subtitle, data = [], dateRange) => {
  // A4 size = 595.28 x 841.89 pt. Printable width = 523.28 pt with 36pt margins.
  const doc = new PDFDocument({ margin: 36, size: 'A4', bufferPages: true });

  doc.pipe(res);

  const logoPath = getLogoPath();

  // Design Tokens
  const navyHeader = '#0B1220';
  const navyDark = '#0F172A';
  const cyanAccent = '#00D9FF';
  const cyanSub = '#0284C7';
  const lightBg = '#F8FAFC';
  const borderLine = '#E2E8F0';
  const textDark = '#0F172A';
  const textMuted = '#64748B';

  // 1. Header with Official CrimePilot Logo and Spacing
  doc.rect(0, 0, 595.28, 98).fill(navyHeader);
  doc.rect(0, 98, 595.28, 3.5).fill(cyanAccent);

  // Draw Logo in Header Top-Left if available
  if (logoPath) {
    try {
      doc.image(logoPath, 36, 24, { width: 44, height: 44 });
    } catch (e) {
      console.warn('Logo image render warning:', e.message);
    }
  }

  const textStartX = logoPath ? 92 : 36;

  doc
    .fillColor(cyanAccent)
    .font('Helvetica-Bold')
    .fontSize(7.5)
    .text('GOVERNMENT OF INDIA // NATIONAL CRIME INTELLIGENCE COMMAND', textStartX, 16, { characterSpacing: 0.8 });

  doc
    .fillColor('#FFFFFF')
    .font('Helvetica-Bold')
    .fontSize(14)
    .text('CRIMEPILOT AI — NATIONAL CRIME INTELLIGENCE PLATFORM', textStartX, 33);

  doc
    .fillColor('#7DD3FC')
    .font('Helvetica-Bold')
    .fontSize(10)
    .text('OFFICIAL CRIME INVESTIGATION REPORT', textStartX, 54);

  doc
    .fillColor('#94A3B8')
    .font('Helvetica')
    .fontSize(7.5)
    .text('CONFIDENTIAL & RESTRICTED DOCUMENT — GOVERNMENT ACCESS ONLY', textStartX, 73);

  // 2. Report Information Cards (2 rows x 3 columns)
  let y = 122;
  const reportId = `NCIP-${Date.now().toString().slice(-6)}`;
  const now = new Date();
  const dateFormatted = now.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const periodFormatted = dateRange || '20 Jul - 31 Jul 2026';

  const infoCards = [
    { label: 'REPORT ID', val: reportId, valColor: cyanSub },
    { label: 'GENERATED DATE', val: dateFormatted, valColor: textDark },
    { label: 'REPORT PERIOD', val: periodFormatted, valColor: textDark },
    { label: 'GENERATED BY', val: 'Admin Command', valColor: textDark },
    { label: 'CLASSIFICATION', val: 'Internal Use', valColor: '#B91C1C' },
    { label: 'STATUS', val: 'Official', valColor: '#15803D' }
  ];

  const colW = 166.4;
  const colGap = 12;
  const cardH = 34;

  infoCards.forEach((card, idx) => {
    const colIdx = idx % 3;
    const rowIdx = Math.floor(idx / 3);
    const cx = 36 + colIdx * (colW + colGap);
    const cy = y + rowIdx * (cardH + 8);

    doc.roundedRect(cx, cy, colW, cardH, 5).fillAndStroke(lightBg, borderLine);
    doc.fillColor(textMuted).font('Helvetica-Bold').fontSize(6.5).text(card.label, cx + 10, cy + 6);
    doc.fillColor(card.valColor).font('Helvetica-Bold').fontSize(9).text(card.val, cx + 10, cy + 17);
  });

  // 3. Independent Statistic Cards with Left Colored Border (Spacious & Premium 68pt height)
  y = 208;
  const totalCases = data.length;
  const solvedCases = data.filter(c => ['Solved', 'Closed'].includes(c.status)).length;
  const pendingCases = data.filter(c => ['Open', 'Under Investigation', 'Reported', 'Pending'].includes(c.status)).length;
  const highPriority = data.filter(c => c.priority === 'High').length;
  const criticalCases = data.filter(c => c.priority === 'Critical').length;

  const statCards = [
    { icon: '📁', label: 'TOTAL CASES', val: totalCases, color: '#0369A1' },
    { icon: '✅', label: 'SOLVED CASES', val: solvedCases, color: '#15803D' },
    { icon: '⏳', label: 'PENDING CASES', val: pendingCases, color: '#B45309' },
    { icon: '⚠️', label: 'HIGH PRIORITY', val: highPriority, color: '#C2410C' },
    { icon: '🚨', label: 'CRITICAL CASES', val: criticalCases, color: '#B91C1C' }
  ];

  const statW = 96.6;
  const statGap = 10;
  const statH = 68; // Increased height by ~26% for spacious, premium look

  statCards.forEach((card, idx) => {
    const cx = 36 + idx * (statW + statGap);
    doc.roundedRect(cx, y, statW, statH, 6).fillAndStroke(lightBg, borderLine);
    doc.rect(cx, y + 2, 4, statH - 4).fill(card.color);

    doc.fillColor(textMuted).font('Helvetica-Bold').fontSize(6.5).text(`${card.icon} ${card.label}`, cx + 10, y + 10, { width: statW - 14 });
    doc.fillColor(card.color).font('Helvetica-Bold').fontSize(18).text(card.val.toString(), cx + 10, y + 32);
  });

  // 4. Two Independent Square Summary Cards
  y = 296;

  const categoryCounts = {};
  const stationCounts = {};
  data.forEach(c => {
    const cat = c.crimeCategory?.name || c.category || 'Unassigned';
    const stn = c.location?.policeStation || c.policeStation || 'HQ Unit';
    categoryCounts[cat] = (categoryCounts[cat] || 0) + 1;
    stationCounts[stn] = (stationCounts[stn] || 0) + 1;
  });

  const summaryW = 252;
  const summaryH = 88;

  // Category Summary Card
  doc.roundedRect(36, y, summaryW, summaryH, 6).fillAndStroke(lightBg, borderLine);
  doc.fillColor(navyDark).font('Helvetica-Bold').fontSize(8.5).text('📊 CRIME CATEGORY SUMMARY', 48, y + 10);

  let catY = y + 28;
  const topCats = Object.entries(categoryCounts).slice(0, 3);
  if (topCats.length === 0) {
    doc.fillColor(textMuted).font('Helvetica').fontSize(8).text('No category records available.', 48, catY);
  } else {
    topCats.forEach(([catName, count]) => {
      const pct = Math.round((count / Math.max(totalCases, 1)) * 100);
      doc.fillColor(textDark).font('Helvetica').fontSize(7.5).text(`• ${catName.slice(0, 16)}: ${count} (${pct}%)`, 48, catY);
      doc.rect(165, catY + 1, 110, 5).fill('#E2E8F0');
      doc.rect(165, catY + 1, Math.min(110, (pct / 100) * 110), 5).fill(cyanSub);
      catY += 18;
    });
  }

  // Police Station Summary Card
  doc.roundedRect(307, y, summaryW, summaryH, 6).fillAndStroke(lightBg, borderLine);
  doc.fillColor(navyDark).font('Helvetica-Bold').fontSize(8.5).text('🏛️ POLICE STATION SUMMARY', 319, y + 10);

  let stnY = y + 28;
  const topStns = Object.entries(stationCounts).slice(0, 3);
  if (topStns.length === 0) {
    doc.fillColor(textMuted).font('Helvetica').fontSize(8).text('No station records available.', 319, stnY);
  } else {
    topStns.forEach(([stnName, count]) => {
      const pct = Math.round((count / Math.max(totalCases, 1)) * 100);
      doc.fillColor(textDark).font('Helvetica').fontSize(7.5).text(`• ${stnName.slice(0, 16)}: ${count} (${pct}%)`, 319, stnY);
      doc.rect(436, stnY + 1, 110, 5).fill('#E2E8F0');
      doc.rect(436, stnY + 1, Math.min(110, (pct / 100) * 110), 5).fill('#10B981');
      stnY += 18;
    });
  }

  // 5. Incident Case Logs Table with Police Station Widest Column & Dynamic Line Wrapping
  y = 406;

  const renderTableHeader = (currentY) => {
    doc.rect(36, currentY, 523.28, 22).fill(navyDark);
    doc.fillColor('#FFFFFF').font('Helvetica-Bold').fontSize(7.5);
    doc.text('CASE ID', 44, currentY + 7, { width: 50 });
    doc.text('CITIZEN NAME', 98, currentY + 7, { width: 72 });
    doc.text('CATEGORY', 174, currentY + 7, { width: 74 });
    doc.text('POLICE STATION', 252, currentY + 7, { width: 110 }); // Widest column
    doc.text('OFFICER', 366, currentY + 7, { width: 68 });
    doc.text('PRIORITY', 438, currentY + 7, { width: 48 });
    doc.text('STATUS', 490, currentY + 7, { width: 64 });
  };

  doc.fillColor(navyDark).font('Helvetica-Bold').fontSize(10).text('INCIDENT CASE LOGS & INVESTIGATION REGISTRY', 36, y);
  y += 18;
  renderTableHeader(y);
  y += 22;

  // No Data State vs Table Rows
  if (data.length === 0) {
    doc.roundedRect(36, y, 523.28, 110, 6).fillAndStroke('#FFFFFF', borderLine);
    doc.fillColor(textDark).font('Helvetica-Bold').fontSize(26).text('📂', 280, y + 16);
    doc.fillColor(navyDark).font('Helvetica-Bold').fontSize(10.5).text('No crime records matched the selected filters.', 86, y + 54, { width: 420, align: 'center' });
    doc.fillColor(textMuted).font('Helvetica').fontSize(8.5).text('Try expanding the report period or modifying the selected filters.', 86, y + 74, { width: 420, align: 'center' });
    y += 120;
  } else {
    data.forEach((item, index) => {
      const caseId = item.crimeId || item.id || `CP-${1000 + index}`;
      const citizenName = item.reportedBy?.name || item.citizenName || item.victimName || 'Anonymous';
      const categoryName = item.crimeCategory?.name || item.category || 'Unassigned';
      const stationName = item.location?.policeStation || item.policeStation || 'HQ Unit';
      const officerName = item.assignedOfficer?.name || item.officer || 'Unassigned';
      const priorityVal = item.priority || 'Medium';
      const statusVal = item.status || 'Open';

      doc.font('Helvetica').fontSize(7.5);
      const stnH = doc.heightOfString(stationName, { width: 108 });
      const citH = doc.heightOfString(citizenName, { width: 70 });
      const catH = doc.heightOfString(categoryName, { width: 74 });
      const offH = doc.heightOfString(officerName, { width: 68 });

      const contentH = Math.max(stnH, citH, catH, offH, 12);
      const rowHeight = Math.max(28, Math.ceil(contentH) + 12);

      if (y + rowHeight > 745) {
        doc.addPage();
        y = 40;
        renderTableHeader(y);
        y += 22;
      }

      const rowBg = index % 2 === 0 ? '#FFFFFF' : '#F8FAFC';
      doc.rect(36, y, 523.28, rowHeight).fillAndStroke(rowBg, '#F1F5F9');

      const textY = y + 7;
      doc.font('Helvetica').fontSize(7.5).fillColor(textDark);
      doc.text(caseId, 44, textY, { width: 50, lineBreak: false });
      doc.text(citizenName, 98, textY, { width: 70, lineBreak: true });
      doc.text(categoryName, 174, textY, { width: 74, lineBreak: true });
      doc.text(stationName, 252, textY, { width: 108, lineBreak: true }); // Wraps cleanly onto line 2 if long
      doc.text(officerName, 366, textY, { width: 68, lineBreak: true });

      // Priority Badge
      let pBg = '#FFEDD5', pTxt = '#9A3412';
      if (priorityVal === 'High') { pBg = '#FEE2E2'; pTxt = '#991B1B'; }
      else if (priorityVal === 'Critical') { pBg = '#FCE7F3'; pTxt = '#9D174D'; }
      else if (priorityVal === 'Low') { pBg = '#DCFCE7'; pTxt = '#166534'; }

      const badgeY = y + Math.floor((rowHeight - 14) / 2);
      doc.roundedRect(438, badgeY, 48, 14, 3).fill(pBg);
      doc.fillColor(pTxt).font('Helvetica-Bold').fontSize(7).text(priorityVal, 438, badgeY + 3, { width: 48, align: 'center' });

      // Status Badge
      let sBg = '#E0F2FE', sTxt = '#0369A1';
      if (['Closed', 'Solved'].includes(statusVal)) { sBg = '#DCFCE7'; sTxt = '#15803D'; }
      else if (['Under Investigation', 'Assigned'].includes(statusVal)) { sBg = '#FEF3C7'; sTxt = '#B45309'; }

      doc.roundedRect(490, badgeY, 64, 14, 3).fill(sBg);
      doc.fillColor(sTxt).font('Helvetica-Bold').fontSize(7).text(statusVal, 490, badgeY + 3, { width: 64, align: 'center' });

      y += rowHeight;
    });
  }

  // 6. Faint Logo & Text Watermark + Footer on all pages
  const totalPages = doc.bufferedPageRange().count;

  for (let i = 0; i < totalPages; i++) {
    doc.switchToPage(i);

    // Footer with Small Logo on Left
    doc.rect(36, 804, 523.28, 1).fill('#CBD5E1');

    if (logoPath) {
      try {
        doc.image(logoPath, 36, 810, { width: 14, height: 14 });
      } catch (e) {}
    }

    const footerTextX = logoPath ? 56 : 36;
    doc
      .fillColor(textMuted)
      .font('Helvetica')
      .fontSize(7.5)
      .text('CrimePilot AI | Official National Crime Intelligence Platform | Official Report', footerTextX, 813)
      .text(`Page ${i + 1} of ${totalPages}`, 420, 813, { align: 'right' });
  }

  doc.end();
};

module.exports = { generateReportPDF };
