# Generated by Django 4.2.23 on 2026-08-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_crime_citizen"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["police_station"], name="core_locati_police__84f102_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["city"], name="core_locati_city_cc1b17_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["district"], name="core_locati_distric_9def0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["state"], name="core_locati_state_2e6af3_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["is_active"], name="core_locati_is_acti_d10f4b_idx"
            ),
        ),
    ]
