# Generated by Django 4.2.23 on 2026-08-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_customuser_role_citizen"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("verified", models.BooleanField(default=False)),
                ("attempts", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email"], name="authenticat_email_e4e215_idx")
                ],
            },
        ),
    ]
