# Generated by Django 4.2.23 on 2026-08-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="profile_picture",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
