# Generated by Django 4.2.23 on 2026-08-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_citizen_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizen",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Verification"),
                    ("verified", "Verified Citizen"),
                    ("rejected", "Rejected"),
                ],
                default="verified",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="citizen",
            constraint=models.UniqueConstraint(
                fields=("identity_type", "identity_number"),
                name="unique_citizen_identity",
            ),
        ),
    ]
