# Generated by Django 6.0.6 on 2026-07-06 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_customuser_role_citizen"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crime",
            name="citizen",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crimes",
                to="authentication.citizen",
            ),
        ),
    ]
