import random
from django.core.mail import send_mail
from django.conf import settings
import logging

logger = logging.getLogger(__name__)

def generate_otp(length=6):
    """Generate a random numeric OTP"""
    return ''.join([str(random.randint(0, 9)) for _ in range(length)])

def send_otp_email(to_email, otp_code):
    """
    Sends an OTP email using Django's SMTP backend.
    """
    subject = "Your CrimePilot AI Verification Code"
    message = f"""
    Dear Citizen,

    Your One-Time Password (OTP) for CrimePilot AI Registration is:

    {otp_code}

    This code is valid for 5 minutes. Please do not share this code with anyone.

    Regards,
    CrimePilot AI Team
    """
    
    html_message = f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; background-color: #0d1117; color: #c9d1d9; padding: 20px; border-radius: 10px; border: 1px solid #30363d;">
        <h2 style="color: #58a6ff; text-align: center; border-bottom: 1px solid #30363d; padding-bottom: 10px;">CrimePilot AI</h2>
        <p style="font-size: 16px;">Dear Citizen,</p>
        <p style="font-size: 16px;">Your One-Time Password (OTP) for registration is:</p>
        <div style="text-align: center; margin: 30px 0;">
            <span style="font-size: 32px; font-weight: bold; background-color: #1f2428; padding: 15px 30px; border-radius: 8px; color: #58a6ff; letter-spacing: 5px;">
                {otp_code}
            </span>
        </div>
        <p style="font-size: 14px; color: #8b949e;">This code is valid for <strong>5 minutes</strong>. Please do not share this code with anyone.</p>
        <hr style="border: 0; border-top: 1px solid #30363d; margin: 20px 0;">
        <p style="font-size: 12px; text-align: center; color: #8b949e;">Securely generated by CrimePilot AI System.</p>
    </div>
    """

    try:
        logger.info(f"[EmailService] Sending OTP to {to_email}")
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[to_email],
            fail_silently=False,
            html_message=html_message
        )
        logger.info(f"[EmailService] Successfully sent OTP to {to_email}")
        return True, "Email sent successfully"
    except Exception as e:
        logger.error(f"[EmailService] Failed to send OTP to {to_email}: {str(e)}")
        return False, str(e)
